### ISSUE TITLE
Compile GRUNT

### ISSUE THREAD

**Issue by jrmora** [bpmn-io/diagram-js-origin#2]
Hi,
I am trying to use it. I do:
1) npm install   result: OK all node_modules charged!
2) grunt            result: Error: Cannot find module 'xx/diagram-js-origin/test/spec/configure-origin.js'

I confirm that the file is exactly in that path.
Thanks if you can help me..

Jaime

**Comment by nikku** [comment]
I cannot reproduce your issue. See below for the stuff I tried and the relevant output:

```
$ git clone git@github.com:bpmn-io/diagram-js-origin.git diagram-js-origin
$ cd diagram-js-origin
$ npm i && grunt
... npm output
Running "jshint:src" (jshint) task
>> 2 files lint free.

Running "karma:single" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket wNjj-uuwopEsEniLL0rR with id 80416543
INFO [framework.browserify]: 1009535 bytes written (1.10 seconds)
INFO [framework.browserify]: bundle built
PhantomJS 1.9.8 (Linux): Executed 1 of 1 SUCCESS (0.039 secs / 0.006 secs)

Done, without errors.
```

**Comment by jrmora** [comment]
Administrador@CARVAJAL-PC /d/soft/bpmn-io/diagram-js-origin
$ npm i && grunt
npm WARN package.json karma-mocha@0.1.10 No README data
load-grunt-tasks@0.3.0 node_modules\load-grunt-tasks
├── findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.11)
└── globule@0.2.0 (lodash@2.4.1, minimatch@0.2.14, glob@3.2.11)
Running "jshint:src" (jshint) task

> > 2 files lint free.

Running "karma:single" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
INFO [framework.browserify]: 1009534 bytes written (10.33 seconds)
INFO [framework.browserify]: bundle built
INFO [Firefox 36.0.0 (Windows 7)]: Connected on socket oCcMMXxQ7LhdSoDQvYFx with
 id 85903060
Firefox 36.0.0 (Windows 7) ERROR
  Error: Cannot find module 'd:/soft/bpmn-io/diagram-js-origin/test/spec/configu
re-origin.js'
  at C:/Users/ADMINI~1/AppData/Local/Temp/f9feadc78e1a73e2791e4c58b08d6a1f7b3098
4f.browserify:1:0 <- node_modules\karma-browserify\node_modules\browserify\node_
modules\browser-pack_prelude.js:1:0

Warning: Task "karma:single" failed. Use --force to continue.

Aborted due to warnings.

Administrador@CARVAJAL-PC /d/soft/bpmn-io/diagram-js-origin
$

**Comment by nikku** [comment]
Thanks for the additional information. You are running into a [karma-browserify](https://github.com/nikku/karma-browserify) + Windows compatibility issue. I have upgraded the library to the latest version (5fdd7375e98f023303e37120e6c923fa5c5c7370). See if it fixes your issue.

**Comment by jrmora** [comment]
Perfect, thank you... It Works!
