### ISSUE TITLE
After upgrading to the latest versions of diagram-js, bpmn-js and origin the visual elements of origrin do no get loaded

### ISSUE THREAD

**Issue by FlexiGit** [bpmn-io/diagram-js-origin#4]
In fact, it's not only the visuals, which don't get loaded. It's the whole module.
When I set a breakpoint in the constructor function in the F12 tools nothing happens. Apparently the breakpoint does not get hit.

**Comment by nikku** [comment]
Please make sure you consume this module via `require('diagram-js-origin').default` or `import OriginModule from 'diagram-js-origin'`.

**Comment by FlexiGit** [comment]
I did:
```javascript
import * as OriginModule from "diagram-js-origin";
```
and
```javascript
additionalModules: [
    ...
    OriginModule,
    ...
],
```

This was working fine before I upgraded the libs.

**Comment by nikku** [comment]
Please don't use wildcard imports. Use the proper default import as mentioned above.

**Comment by FlexiGit** [comment]
My bad. I could swear, that it was working before upgrading with the wildcard ;-)

But anyway, why is this working then?
```typescript
import * as PropertiesPanelModule from "bpmn-js-properties-panel";
import OriginModule from "diagram-js-origin";
```

PS: I'm using Typescript

**Comment by nikku** [comment]
The question is, what would you like to achieve using the wildcard import?
