### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by zhuangxiaohui** [bpmn-io/diagram-js-origin#6]
[This package](https://www.jsdelivr.com/package/npm/detect-indent) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by nikku** [comment]
How is `This package => https://www.jsdelivr.com/package/npm/detect-indent` related to this library?
